### ISSUE TITLE
Water Recipe Issues [1.19.2]

### ISSUE THREAD

**Issue by captaintekton** [jetpacker06/Create-Broken-Bad#10]
1.19.2 - 43.2.17 (forge)
Create: Broken Bad (createbb-1.19.2-2.2.1.jar), seems to cause issues with mods that use fluid water in their recipes. I have tested this with Mekanism (Mekanism-1.19.2-10.3.8.477.jar), Immersive engineering (ImmersiveEngineering-1.19.2-9.2.2-165.jar), and Extreme Reactors (ExtremeReactors2-1.19.2-2.0.64.jar).

Recipes that consume water do not appear in JEI, and the machines from those mods will not accept fluid water at all.

Does create broken bad change the way Minecraft fluid water is registered or something? Like here: 
src/main/java/com/jetpacker06/CreateBrokenBad/registrate/RFluids.java
That may be the problem, but I don't know a whole lot about forge modding, so it's just a guess. But the issue is definitely caused by this mod, as all issues are resolved when it is removed.

**Comment by jetpacker06** [comment]
This should be fixed in the newest updates, thanks for reporting.
