### ISSUE TITLE
Ephedra breaks after being planted.

### ISSUE THREAD

**Issue by crispeeweevile** [jetpacker06/Create-Broken-Bad#11]
So, after the recent fix, I'm now able to plant the Ephedra, but now, the second it's planted, it breaks, and the dirt becomes "unfarmed" (as if it was trampled)

**Comment by jetpacker06** [comment]
Sorry, I thought I fixed it already but then I redid a bunch of code and forgot to bring the fix with it. It is fixed now, thanks for reporting.
