### ISSUE TITLE
[1.19.2 and 1.20.1] Adding trades to Nitwit villagers crashed Repurposed Structures 

### ISSUE THREAD

**Issue by TelepathicGrunt** [jetpacker06/Create-Broken-Bad#22]
I gotten this bug report for my mod
https://github.com/TelepathicGrunt/RepurposedStructures/issues/309

Upon closer look, it appears this mod is adding trades to all villagers including Nitwit villagers. But only to level 1 and 2 trades. And since Nitwits have no trades by default, the missing level 0 trades then causes my mod's code to blow up
https://github.com/jetpacker06/Create-Broken-Bad/blob/39ca15be502c2d8c78110e74f7166d9e7472310f/src/main/java/com/jetpacker06/CreateBrokenBad/register/AllEvents.java#L26-L33

Since Nitwits are not tradeable, this seems like a bug on Create Broken Bad side. Try and prevent adding trades to nitwits and that should make everything all good again

**Comment by jetpacker06** [comment]
Thanks for letting me know, i just released a fix for this which will be on Curseforge soon.
