### ISSUE TITLE
error in russian translate 

### ISSUE THREAD

**Issue by OOO145236** [jetpacker06/Create-Broken-Bad#25]
![зображення_2023-12-04_112854809](https://github.com/jetpacker06/Create-Broken-Bad/assets/121662295/b54764b7-f23f-44a7-82dd-48c267ed2dc6)
in translate this called "blue amphetamine" but this is blue methamphetamine
change амфетамин > метамфетамин

**Comment by jetpacker06** [comment]
Ill take your word for it, fixes coming soon
