### ISSUE TITLE
Conflict with Mekanism

### ISSUE THREAD

**Issue by sergwey** [jetpacker06/Create-Broken-Bad#5]
Launching Create: Broken Bad with Mekanism causes Ethylene recipe to completely disappear from Mekanism. 
Steps to reproduce:
1. Install Mekanism, Create, Create:Broken Bad
2. Try to make ethylene with its basic recipe(water, hydrogen and biofuel in pressurised reaction chamber(PRC))
3. Failure(Can't even put these items in chamber)

(Sorry for featuring other mod)

**Comment by captaintekton** [comment]
Having the same issue and opened a new issue

**Comment by jetpacker06** [comment]
Should be fixed in the newest version, thanks for reporting.
