### ISSUE TITLE
Broken bad seems to disable all mob spawning in oceans

### ISSUE THREAD

**Issue by cwayyyy** [jetpacker06/Create-Broken-Bad#8]
Spent a few minutes trying to figure out which mod was causing the issue, and narrowed it down to here.

**Comment by maxwellstull** [comment]
This also happened with me. Spent the better part of an hour narrowing it down to Broken Bad. Commenting so its known this is an actual issue.

**Comment by S1532011** [comment]
This is a recurring issue across many of the newer mod releases. I and 20 others in a server tested this mod with the same results: No water-based mobs spawn (cod, salmon, drowned, tropical fish, squid, glow squid, and even other modded aquatic mobs). I have started trying to figure out what the issue could be, but I am still a beginner to mod development for Minecraft. If you have any questions about the issue or any of my finding my discord is: foxmaster198

**Comment by MalachiMaenle** [comment]
I've remade nearly all of the mod without adding in any fluids, and something still seems to be breaking water mob spawning (except drowned). If you spawn mobs using spawn eggs, cod and salmon AI is also broken, but squid and guardians still function normally
![2023-07-18_02 12 19](https://github.com/jetpacker06/Create-Broken-Bad/assets/89474296/e80071b9-ac0f-467b-9a1b-d29551a430fa)

**Comment by MalachiMaenle** [comment]
I fixed it... Just remove this file
![Screenshot 2023-07-18 022746](https://github.com/jetpacker06/Create-Broken-Bad/assets/89474296/4c667beb-0c1a-4fa9-a7f6-1cc2a11353e1)

**Comment by MalachiMaenle** [comment]
I finished my recreation/port to 1.19.2, fixing all the deprecated code, and the water mob spawning issues.

**Comment by jetpacker06** [comment]
Thanks for reporting, fixed in newest version
