### ISSUE TITLE
Ephedra unable to be planted?

### ISSUE THREAD

**Issue by crispeeweevile** [jetpacker06/Create-Broken-Bad#9]
Yo, so I'm using Create 0.5.1C, and CreateBB 2.2.1
I managed to get some Ephedra Seeds, but they seem to not be plantable, I tried on Farmland, Grass, in water, and next to water. Unfortunately none of them worked, so I guess they just cannot be planted.

**Comment by jetpacker06** [comment]
Thanks for reporting, fixed in newest version
